# Nginx Alpine 이미지 사용
FROM nginx:alpine
# Nginx 이미지에 포함된 기본 설정 파일 삭제
RUN rm /etc/nginx/conf.d/default.conf
# 커스텀 Nginx 설정 파일 복사
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
# 포트 노출. 문서화 목적
EXPOSE 80 443
# Nginx 실행 , 포그라운드 실행 (백그라운드로 가면 Docker 컨테이너가 즉시 종료됨)
CMD ["nginx", "-g", "daemon off;"]
